### ISSUE TITLE
Integração FMOD com Godot

### ISSUE THREAD

**Issue by gumaciel** [gumaciel/awesome-game-jam-01#13]
Export:

- Android
- HTML5
- Windows
- Linux
- MacOS

**Comment by karlacorrea** [comment]
Feito instalaçãp do plugin FMOD

**Comment by gumaciel** [comment]
Ty @karlacorrea

**Comment by gumaciel** [comment]
Infelizmente o plugin não tem suporte pra HTML5, impossibilitando o uso no projeto
